config/routes.rb
Rails.application.routes.draw do
	root 'plans#index'
	post '/plans/:plan_id/addcourse/:id' => 'plans#addcourse'
	post '/plans/:plan_id/removecourse/:id' => 'plans#removecourse'
	post '/plans/:plan_id/removeyear/:id' => 'plans#removeyear'
	post '/plans/:plan_id/addyear/:id' => 'plans#addyear'
  resources :courses
  resources :plans
  devise_for :users, :controllers => {:registrations => 'registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
	has_many :term_courses
	has_many :terms, through: :term_courses
end

app/models/plan.rb
class Plan < ApplicationRecord
	belongs_to(:user)
	has_many :terms
	
end

app/models/term.rb
class Term < ApplicationRecord
  belongs_to :plan
  has_many :term_courses
 	has_many :courses, through: :term_courses
end

app/models/term_course.rb
class TermCourse < ApplicationRecord
  belongs_to :term
  belongs_to :course
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many(:plans)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name)
    end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]
  before_action :set_plan_course, only: [:addcourse, :removecourse]
  before_action :set_plan_year, only: [:addyear, :removeyear]
  skip_before_action :verify_authenticity_token

  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.where(user_id: current_user.id)
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
    @id = @plan.id
    @name = @plan.name
    @major = @plan.major
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end
  
  def addcourse
    @term = Term.find_by(plan: @plan.id, semester: params[:semester], year: params[:year])
    TermCourse.create(term: @term, course: @course)
  end
  
  def removecourse
    @term = Term.find_by(plan: @plan.id, semester: params[:semester], year: params[:year])
    @termcourse = TermCourse.find_by(term: @term, course: @course)
    TermCourse.delete(@termcourse)
  end
  
  def addyear
    @term = Term.exists?(plan: @plan, year: params[:year])
    if @term
      puts "Not added"
      puts @term
    else
      Term.create([{plan: @plan, semester: "Fall", year: params[:year]}, {plan: @plan, semester: "Spring", year: params[:year]}, {plan: @plan, semester: "Summer", year: params[:year]}])

    end
    #Term.new()
    #Term.new(plan: @plan, semester: "Summer", year: params[:year])
  end
  
  
  def removeyear
    @year = Term.where(plan: @plan, year: params[:id])
    # @termcourse = TermCourse.where(term: @term, course: @course)
    Term.delete(@year)
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)
    @plan.user_id = current_user.id
    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end
    def set_plan_course
      @plan = Plan.find(params[:plan_id])
      @course = Course.find_by(cid: params[:id])
    end
    
    def set_plan_year
      @plan = Plan.find(params[:plan_id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params.require(:plan).permit(:name, :user_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
   before_filter :update_sanitized_params

   def update_sanitized_params
       devise_parameter_sanitizer.permit(:sign_up, keys: [:login, :email, :password, :password_confirmation])    
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/courses/_form.html.erb
<%= form_for(course) do |f| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/layouts/_header.html.erb
<header> 
   <h1>Welcome to the Academic Planning Tool</h1>
   <% if user_signed_in?%>
      <h3>Welcome, <%= current_user.login %></h3>
      <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
   <% else %>
      <%= link_to "Sign In", new_user_session_path, :method => :get %>
      <%= link_to "Sign up", new_user_registration_path, :method => :get %>
   <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proj6</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    
  </body>
</html>

app/views/plans/_form.html.erb
<%= form_for(plan) do |f| %>
  <% if plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plans/edit.html.erb
<h1>Editing Plan</h1>

<%= render 'form', plan: @plan %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
<p id="notice"><%= notice %></p>
<div class="plans">
  <h1 class="pageHeader">Plans</h1>
  
  <table>
    <thead>
      <tr>
        <% if current_user.admin? %>
            <th>Student</th>
          <% end %>
        <th>Name</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>
  
    <tbody>
       <% if current_user.admin? %>
          <% @plans = Plan.all %>
        <% end %>  
         
      <% @plans.each do |plan| %>
        <tr>
           <% if current_user.admin? %>
              <td><%= plan.student %></td>
           <% end %>  
          <td><%= plan.name %></td>
          <td><%= link_to 'Show', plan %></td>
          <td><%= link_to 'Edit', edit_plan_path(plan) %></td>
          <td><%= link_to 'Destroy', plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<%= link_to 'New Plan', new_plan_path %>

app/views/plans/new.html.erb
<h1>New Plan</h1>

<%= render 'form', plan: @plan %>

<%= link_to 'Back', plans_path %>